# 1. Create a 3x3x3 array with random values 

In [93]:
import numpy as np
A = np.empty((3,3,3))
print(A)

# B = np.random.randint(100, size =(3,3,3))
# print(B)
# B = np.random.random(size = (3,3,3))
# print(B)
# B = np.random.rand(3,3,3)
# print(B)

[[[0.56321649 0.28019952 0.84859617]
  [0.9279723  0.73281188 0.30563038]
  [0.50183073 0.24664629 0.53973183]]

 [[0.23019802 0.90915827 0.22190156]
  [0.58666929 0.04335138 0.20606783]
  [0.38972966 0.02933981 0.33843729]]

 [[0.71642748 0.12535059 0.83350356]
  [0.77193173 0.75387263 0.60796161]
  [0.23676932 0.12047661 0.21746639]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
import numpy as np
v = [1,2,3,4]
arr_A = np.diag(v, k = -1)
print(arr_A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [34]:
import numpy as np
check = np.zeros((8,8), dtype = int)
check[1::2, ::2] = 1
check[::2, 1::2] = 1
print(check)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [161]:
import numpy as np
print("Original Array: \n")
OG_Arr = np.random.randint(1,9, size =(5,3))
print(OG_Arr)
norm = np.linalg.norm(OG_Arr)
print("\nNorm Value:",norm)
if(norm>0):
    print("\nNormailzed Array: \n")
    Norm_Arr = OG_Arr/norm
    print(Norm_Arr)

Original Array: 

[[8 6 6]
 [2 7 2]
 [3 4 3]
 [8 2 4]
 [3 5 6]]

Norm Value: 19.519221295943137

Normailzed Array: 

[[0.40985242 0.30738931 0.30738931]
 [0.1024631  0.35862086 0.1024631 ]
 [0.15369466 0.20492621 0.15369466]
 [0.40985242 0.1024631  0.20492621]
 [0.15369466 0.25615776 0.30738931]]


# 5.  How to find common values between two arrays?

In [45]:
import numpy as np
Arr1 = np.array([1,2,3,6,8,9])
Arr2 = np.array([10,3,9,5,7])
print("Array1:",Arr1)
print("Array2:",Arr2)
print("Common values:",np.intersect1d(Arr1,Arr2))

Array1: [1 2 3 6 8 9]
Array2: [10  3  9  5  7]
Common values: [3 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [49]:
import numpy as np
today     = np.datetime64('today')
print("Today: ",today)

yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yestraday: ",yesterday)

tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow: ",tomorrow)

Today:  2020-07-27
Yestraday:  2020-07-26
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [68]:
import numpy as np
A = np.random.randint(0,2,5)
print(A)
B = np.random.randint(0,2,5)
print(B)
print(np.array_equal(A,B))

[1 1 0 1 0]
[1 1 1 0 0]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [80]:
import numpy as np
x = np.random.random(10)
print("Actual Vector:\n",x)
x[x.argmax()] = 0
print("Maximum value replaced Vector:")
print(x)


Actual Vector:
 [0.5931552  0.80936249 0.79741431 0.09733676 0.90222546 0.35605896
 0.36083041 0.59385331 0.46996208 0.97583458]
Maximum value replaced Vector:
[0.5931552  0.80936249 0.79741431 0.09733676 0.90222546 0.35605896
 0.36083041 0.59385331 0.46996208 0.        ]


# 9. How to print all the values of an array?

In [162]:
import numpy as np
np.set_printoptions(threshold=np.inf)
k = np.zeros((4,4))
print(k)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [105]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 2)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.29960849 0.56741536]
 [0.91374651 0.48121287]
 [0.40488374 0.84396355]
 [0.53933563 0.74312934]
 [0.17722255 0.32910728]]

Subtract the mean of each row of the said matrix:

[[-0.13390343  0.13390343]
 [ 0.21626682 -0.21626682]
 [-0.21953991  0.21953991]
 [-0.10189685  0.10189685]
 [-0.07594236  0.07594236]]


## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [136]:
import numpy as np
vec_A = np.arange(10)
vec_B = np.random.randint(0, 9, size = 4)
vec_B = np.unique(vec_B)
print("OG Vector:",vec_A)
print("Index Vector:",vec_B)
for x in vec_B:
    vec_A[x] =vec_A[x]+1
print("Result Vector:",vec_A)

OG Vector: [0 1 2 3 4 5 6 7 8 9]
Index Vector: [1 3 4 6]
Result Vector: [0 2 2 4 5 5 7 7 8 9]


# 12.How to get the diagonal of a dot product?

In [133]:
A = np.random.randint(0,10,(3,3))
print(A)
B= np.random.randint(0,10,(3,3))
print(B)
#Slow version
C=np.dot(A, B)
print(C)
D=np.diag(C)
print(D)

[[6 4 5]
 [8 0 0]
 [4 4 9]]
[[2 7 2]
 [9 6 5]
 [2 0 4]]
[[58 66 52]
 [16 56 16]
 [62 52 64]]
[58 56 64]


# 13.How to find the most frequent value in an array?

In [128]:
x = np.random.randint(0, 10, 15)
print("Original array:",x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array: [7 8 6 6 4 6 2 7 5 4 6 0 9 2 8]
Most frequent value in the above array:
6


# 14.How to get the n largest values of an array

In [138]:
import numpy as np
x = np.array([13,8,6,34,2,7,32,12])
print("Original array:")
print(x)
n = int(input("Enter the number (n):"))
print (x[np.argsort(x)[-n:]])

Original array:
[13  8  6 34  2  7 32 12]
Enter the number (n):4
[12 13 32 34]


# 15.How to create a record array from a regular array?

In [163]:
import numpy as np
arr = np.array([["Jack", "Nick"],  #names
               [25.6, 18.2],       #Age
               [11, 19]])          #BirthDates
print("Original Array:")
print(arr)

recordsrd_arr = np.core.records.fromarrays(arr,names='a,b,c')
print("\nRecord Array:")
print(recordsrd_arr)

# print(recordsrd_arr.a)
# print(recordsrd_arr.b)
# print(recordsrd_arr.c)
# print(recordsrd_arr[1])
# print(recordsrd_arr[0])

Original Array:
[['Jack' 'Nick']
 ['25.6' '18.2']
 ['11' '19']]

Record Array:
[('Jack', '25.6', '11') ('Nick', '18.2', '19')]
